---
# Custom Plugins

- repo: sgur/vim-editorconfig
- repo: itchyny/vim-gitbranch
- repo: itchyny/vim-parenmatch
- repo: vim-airline/vim-airline
- repo: vim-airline/vim-airline-themes
- repo: arcticicestudio/nord-vim
- repo: vimoutliner/vimoutliner
- repo: taketwo/vim-ros
- repo: zxqfl/tabnine-vim
- repo: scrooloose/syntastic
- repo: lervag/vimtex
- repo: vimwiki/vimwiki
